
-- Versión MySQL:	5.7.24
-- Versión de PHP: 	7.2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: cybergames
--

-- --------------------------------------------------------

CREATE DATABASE IF NOT EXISTS cybergames DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cybergames;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla ARTICULOS
--

DROP TABLE IF EXISTS ARTICULOS;
CREATE TABLE IF NOT EXISTS ARTICULOS (
  ID int(5) NOT NULL,
  NOMBRE varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  TIPO varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  PLATAFORMA varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  STOCK int(4) DEFAULT NULL,
  PCOMPRA float(6,2) DEFAULT NULL,
  PVENTA float(6,2) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla ARTICULOS
--

INSERT INTO ARTICULOS (ID, NOMBRE, TIPO, PLATAFORMA, STOCK, PCOMPRA, PVENTA) VALUES
(0, 'DRAGON BALL Z - HYPER DIMENSION', 'LUCHA', 'SONY PLAYSTATION', 3, 60.00, 70.00),
(1, 'CRAZY TAXY', 'ACCION/AVENTURA', 'SEGA DREAMCAST', 2, 50.00, 55.00),
(2, 'METAL GEAR SOLID', 'ACCION/AVENTURA', 'SONY PLAYSTATION', 7, 90.00, 190.00),
(3, 'THE LEGEND OF ZELDA: OCARINA OF TIME', 'ROL', 'NINTENDO N64', 1, 60.00, 90.00),
(4, 'PANZER DRAGOON', 'ACCION/AVENTURA', 'SEGA SATURN', 10, 50.00, 195.00),
(5, 'SEGA RALLY - CHAMPIONSHIP EDITION', 'DEPORTES', 'SEGA DREAMCAST', 0, 40.00, 90.00),
(6, 'SONIC THE HEDGEHOG', 'PLATAFORMAS', 'SEGA MASTER SYSTEM', 0, 30.00, 45.00),
(7, 'SONIC THE HEDGEHOG', 'PLATAFORMAS', 'SEGA MEGA DRIVE', 0, 50.00, 60.00),
(9, 'PSY OPS', 'ACCION/AVENTURA', 'SONY PLAYSTATION 2', 2, 25.00, 40.00),
(10, 'SHINOBI X', 'PLATAFORMAS', 'SEGA SATURN', 0, 90.00, 120.00),
(11, 'SMASH BROS', 'ACCION/AVENTURA', 'NINTENDO SWITCH', 4, 65.00, 70.00),
(12, 'CONTRA', 'PLATAFORMAS', 'NINTENDO NES', 3, 20.00, 49.00),
(13, 'METAL SLUG', 'PLATAFORMAS', 'NEO-GEO', 1, 231.00, 500.00),
(14, 'TENKKA: CONDICIÓN HUMANA', 'AVENTURA GRÁFICA', 'SONY PLAYSTATION', 0, 30.00, 40.00);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla CLIENTES
--

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE IF NOT EXISTS CLIENTES (
  ID varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,
  NOMBRE varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  APELLIDOS varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  TELEFONO1 varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,
  TELEFONO2 varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  EMAIL varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  DIRECCION varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  CPOSTAL int(5) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla CLIENTES
--

INSERT INTO CLIENTES (ID, NOMBRE, APELLIDOS, TELEFONO1, TELEFONO2, EMAIL, DIRECCION, CPOSTAL) VALUES
('00567898X', 'DAVID', 'ÜBBER ROBLEDÓN', '612098770', '', 'DUBBER@TSYSTEMAS.ORG', 'AVENIDA DE LA CONSTITUCIÓN, 29', 28341),
('78998023V', 'ALBERTO', 'MERINO MONZÓN', '690989090', '', 'AMERINO@GRUPOALTURA.NET', 'CALLE VALENCIA, 12', 28345);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla FACTURAS
--

DROP TABLE IF EXISTS FACTURAS;
CREATE TABLE IF NOT EXISTS FACTURAS (
  IDFACT int(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  FECHA date NOT NULL,
  IDCLI varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,
  SUBTOTAL float(6,2) NOT NULL,
  IVA float(6,2) NOT NULL,
  TOTAL float(6,2) NOT NULL,
  PRIMARY KEY (IDFACT)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla FACTURAS
--

INSERT INTO FACTURAS (IDFACT, FECHA, IDCLI, SUBTOTAL, IVA, TOTAL) VALUES
(00001, '2019-02-17', '78998023V', 40.00, 8.40, 48.40);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla PLATAFORMAS
--

DROP TABLE IF EXISTS PLATAFORMAS;
CREATE TABLE IF NOT EXISTS PLATAFORMAS (
  IDPLAT int(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  PLATAFORMA varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (IDPLAT),
  UNIQUE KEY PLATAFORMA (PLATAFORMA)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla PLATAFORMAS
--

INSERT INTO PLATAFORMAS (IDPLAT, PLATAFORMA) VALUES
(0000000017, 'ATARI'),
(0000000016, 'NEO-GEO'),
(0000000004, 'NINTENDO GAMECUBE'),
(0000000003, 'NINTENDO N64'),
(0000000001, 'NINTENDO NES'),
(0000000002, 'NINTENDO SNES'),
(0000000006, 'NINTENDO SWITCH'),
(0000000005, 'NINTENDO WII'),
(0000000011, 'SEGA DREAMCAST'),
(0000000008, 'SEGA GAME GEAR'),
(0000000007, 'SEGA MASTER SYSTEM'),
(0000000009, 'SEGA MEGA DRIVE'),
(0000000010, 'SEGA SATURN'),
(0000000012, 'SONY PLAYSTATION'),
(0000000013, 'SONY PLAYSTATION 2'),
(0000000014, 'SONY PLAYSTATION 3'),
(0000000015, 'SONY PLAYSTATION 4');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla TIPOS
--

DROP TABLE IF EXISTS TIPOS;
CREATE TABLE IF NOT EXISTS TIPOS (
  IDTIP int(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  TIPO varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (IDTIP),
  UNIQUE KEY TIPO (TIPO)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla TIPOS
--

INSERT INTO TIPOS (IDTIP, TIPO) VALUES
(0000000001, 'ACCION/AVENTURA'),
(0000000016, 'AVENTURA GRÃFICA'),
(0000000017, 'CONDUCCIÃ“N'),
(0000000002, 'DEPORTES'),
(0000000010, 'DISPAROS'),
(0000000003, 'ESTRATEGIA'),
(0000000004, 'FPS'),
(0000000009, 'LUCHA'),
(0000000012, 'NULL'),
(0000000005, 'PLATAFORMAS'),
(0000000006, 'ROL'),
(0000000007, 'SIMULACION'),
(0000000008, 'SURVIVAL HORROR');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla USUARIOS
--

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE IF NOT EXISTS USUARIOS (
  UID int(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  USERNAME varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  PASS varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  NOMBRE varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  APELLIDOS varchar(35) COLLATE utf8mb4_unicode_ci NOT NULL,
  ADMIN tinyint(4) NOT NULL,
  PRIMARY KEY (UID),
  UNIQUE KEY USERNAME (USERNAME)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla USUARIOS
--

INSERT INTO USUARIOS (UID, USERNAME, PASS, NOMBRE, APELLIDOS, ADMIN) VALUES
(0000000012, 'PRODRIGUEZ', '$2y$10$QqwMY2p.oX.ic4ca9FQFw.VjKlPVk4QzX48g/APYMoL4KQ4Bx8JmC', 'PABLO', 'RODRíGUEZ GARCíA', 0),
(0000000013, 'ROOT', '$2y$10$gXRUdE3BJMeeyTfIFQNRPuesXjt3eJdnpdgLc6rF2UclBAO3YuZtW', '-', 'ROOT', 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla VENTAS
--

DROP TABLE IF EXISTS VENTAS;
CREATE TABLE IF NOT EXISTS VENTAS (
  IDVENTA int(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  FVENTA date NOT NULL,
  IDCLI varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,
  IDART int(5) NOT NULL,
  CANTIDAD int(5) NOT NULL,
  VALOR float(6,2) NOT NULL,
  PRIMARY KEY (IDVENTA),
  KEY FK_VENT_CLI (IDCLI),
  KEY FK_VENT_ART (IDART)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla VENTAS
--
ALTER TABLE VENTAS
  ADD CONSTRAINT FK_VENT_ART FOREIGN KEY (IDART) REFERENCES ARTICULOS (ID),
  ADD CONSTRAINT FK_VENT_CLI FOREIGN KEY (IDCLI) REFERENCES CLIENTES (ID);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

--
-- Usuario: cybergames. Será el usuario operador para la aplicación.
--

CREATE USER IF NOT EXISTS 'cybergames'@'localhost' IDENTIFIED BY 'cybergames';
GRANT USAGE ON *.* TO 'cybergames'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER ON cybergames.* TO 'cybergames'@'localhost';
